name: CI/CD Pipeline with DockerHub
#push to master
on:
  push:
    branches: [master]
#jobs

jobs:
  build-and-push:
    name: Build &amp; Push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build -t ${{
          secrets.DOCKERHUB_USERNAME }}/nodeapp:latest .
      - name: Push image to DockerHub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME
          }}/nodeapp:latest
#deployment
  deploy:
    name: Deploy to EC2 via Docker Compose
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy via SSH with Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:

          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/DevopsProject
            docker-compose down  # stop and
            remove existing containers
            docker-compose pull
            docker-compose up -d --build

#final